services:
  api_nginx:
    image: nginx:1.28-alpine
    container_name: api_nginx
    depends_on:
      - api_app
    ports:
      - "8015:80"
    volumes:
      - ./backend:/var/www/html:ro
      - ./docker/backend/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - app_net

  api_app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: api_app
    environment:
      APP_ENV: ${APP_ENV:-local}
      APP_DEBUG: "true"
      APP_URL: ${APP_URL:-http://localhost:8015}
      FRONTEND_URL: ${FRONTEND_URL:-http://localhost:5173}
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: ${DB_DATABASE:-laravel}
      DB_USERNAME: ${DB_USERNAME:-laravel}
      DB_PASSWORD: ${DB_PASSWORD:-secret}
    volumes:
      - ./backend:/var/www/html
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - app_net

  mysql:
    image: mysql:8.0
    container_name: api_mysql
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ${DB_DATABASE:-laravel}
      MYSQL_USER: ${DB_USERNAME:-laravel}
      MYSQL_PASSWORD: ${DB_PASSWORD:-secret}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - app_net

  web:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: web_frontend
    working_dir: /app
    ports:
      - "5173:5173"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - HOST=0.0.0.0
      - VITE_API_URL=${VITE_API_URL:-http://localhost:8015}
    volumes:
      - ./frontend:/app
      - node_modules_front:/app/node_modules
    networks:
      - app_net

  supervisor:
    build:
      context: .
      dockerfile: ./docker/supervisor/Dockerfile
    container_name: api_supervisor
    command:
      ["/usr/bin/supervisord", "-c", "/etc/supervisor/conf.d/supervisord.conf"]
    environment:
      APP_ENV: local
      APP_DEBUG: "true"
      APP_URL: ${APP_URL:-http://localhost:8015}
      FRONTEND_URL: ${FRONTEND_URL:-http://localhost:5173}
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: ${DB_DATABASE:-laravel}
      DB_USERNAME: ${DB_USERNAME:-laravel}
      DB_PASSWORD: ${DB_PASSWORD:-secret}
    volumes:
      - ./backend:/var/www/html
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - app_net

volumes:
  mysql_data:
  node_modules_front:

networks:
  app_net:
    driver: bridge
